[package]
name = "one_user"
version = "0.1.0"
authors = ["Error1000"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
lazy_static = "*"
bitvec = "*"
syn = "*"
quote = "*"